### ISSUE TITLE
ToDo::Implove

### ISSUE THREAD

**Issue by project-pp** [project-pp/nazuna#4]
At this moment...

- [x] cache .json http requests
- [x] implement "EXECUTE" command; to run as the specified version node.exe
- [x] implement "EXECUTE.NPM" command; to run npm associated with the specified version.
